### ISSUE TITLE
[Feature Requests] Add built-in video player.

### ISSUE THREAD

**Issue by arranoust** [pratham-jaiswal/anifuri#1]
Please add video player in the app without needing 3rd party video player, and add option to change subtitles. 😁

**Comment by pratham-jaiswal** [comment]
Just waiting for the custom subtitle track feature in [expo-video](https://docs.expo.dev/versions/unversioned/sdk/video/).

The following was stated by the expo devs in their recent [blog](https://expo.dev/blog/expo-video-a-simple-powerful-way-to-play-videos-in-apps):
> In future releases of expo-video it will be possible to add custom subtitles to your VideoSource.

Once the custom subtitle feature will be up, I'll update the app!

**Comment by pratham-jaiswal** [comment]
An inbuilt video player has been added in [v0.5.0](https://github.com/pratham-jaiswal/anifuri/releases/tag/v0.5.0). However, it currently **does not** support subtitles unless they are hardcoded into the streaming video.

I will add support for custom subtitles to the inbuilt video player as soon as the feature becomes feasible. Until then, VLC can still be used for playing videos with subtitles.

**Comment by arranoust** [comment]
oh it would be great if the inbuilt video player could display subtitles and also have an option to change the subtitle language 🤩🤩
